class ColabArgs():
    def __init__(self,
                 output_dir,
                 model_type,
                 should_continue=False,
                 model_name_or_path=None,
                 mlm=True,
                 mlm_probability=0.15,
                 config_name=None,
                 tokenizer_name=None,
                 cache_dir=None,
                 block_size=-1,
                 do_train=True,
                 per_gpu_train_batch_size=4,
                 gradient_accumulation_steps=1,
                 learning_rate=1e-5,
                 weight_decay=0.0,
                 adam_epsilon=1e-8,
                 max_grad_norm=1.0,
                 num_train_epochs=1,
                 max_steps=-1,
                 log_dir=".",
                 warmup_steps=0,
                 local_rank=-1,
                 logging_steps=500,
                 save_steps=500,
                 save_total_limit=5,
                 no_cuda=False,
                 overwrite_output_dir=False,
                 overwrite_cache=False,
                 seed=42,
                 device='cuda'):
        self.output_dir = output_dir
        self.model_type = model_type
        self.should_continue = should_continue
        self.model_name_or_path = model_name_or_path
        self.mlm = mlm
        self.mlm_probability = mlm_probability
        self.config_name = config_name
        self.tokenizer_name = tokenizer_name
        self.cache_dir = cache_dir
        self.block_size = block_size
        self.do_train = do_train
        self.per_gpu_train_batch_size = per_gpu_train_batch_size
        self.gradient_accumulation_steps = gradient_accumulation_steps
        self.learning_rate = learning_rate
        self.weight_decay = weight_decay
        self.adam_epsilon = adam_epsilon
        self.max_grad_norm = max_grad_norm
        self.num_train_epochs = num_train_epochs
        self.max_steps = max_steps
        self.log_dir = log_dir
        self.warmup_steps = warmup_steps
        self.local_rank = local_rank
        self.logging_steps = logging_steps
        self.save_steps = save_steps
        self.save_total_limit = save_total_limit
        self.no_cuda = no_cuda
        self.overwrite_output_dir = overwrite_output_dir
        self.overwrite_cache = overwrite_cache
        self.seed = seed
        self.device=device